# Generated by Django 5.0 on 2023-12-12 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Roll', models.IntegerField()),
                ('City', models.CharField(max_length=100)),
                ('Grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentInfo.grade')),
            ],
        ),
    ]
